name: login
description: Modelo de login.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_launcher_icons: ^0.9.2
  google_sign_in: ^5.3.3
  equatable: ^2.0.3
  firebase_auth: ^3.3.19
  firebase_core: ^1.17.1
  bloc: ^8.0.2
  flutter_bloc: ^8.0.1
  flow_builder: ^0.0.9
  formz: ^0.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  image_path_ios: 'assets/icon/icon.png'
  image_path_android: 'assets/icon/icon.png'
  android: true
  ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icon/
    - assets/logo/
    - assets/treino_peito/